#!/usr/bin/with-contenv bash

source /helpers/logger.sh

log_info "********** Checking if we are running on an RPi **********"
# Check if we are running on an RPi3/CM3 or RPi4/CM4
# Hardware revision table is found here: 
# https://github.com/raspberrypi/documentation/blob/develop/documentation/asciidoc/computers/raspberry-pi/revision-codes.adoc#new-style-revision-codes-in-use
OUTPUT=$(cat /proc/cpuinfo | grep 'Revision' | awk '{print $3}')
case "$OUTPUT" in
    "a02082" | "a020a0" | "a020d3" | "a020d4" | "a22082" | "a220a0" | "a32082" | "a52082" | "a22083" | "a02100")
        export VISERON_RASPBERRYPI3=true
        printf "true" > /var/run/environment/VISERON_RASPBERRYPI3
        log_info "Running on an RPi3"
        ;;

    "a03111" | "b03111" | "b03112" | "b03114" | "b03115" | "c03111" | "c03112" | "d03114" | "c03115" | "d03114" | "d03115" | "c03130" | "a03140" | "b03140" | "c03140" | "d03140")
        export VISERON_RASPBERRYPI4=true
        printf "true" > /var/run/environment/VISERON_RASPBERRYPI4
        log_info "Running on an RPi4"
        ;;

    *)
        log_info "Not running on any supported RPi"
esac
log_info "*********************** Done *****************************"
