#!/usr/bin/with-contenv bash

source /helpers/logger.sh

log_info "********** Checking if we are running on an RPi **********"
# Check if we are running on an RPi3/CM3/Zero2W or RPi4/CM4/400
# Hardware revision table is found here: 
# https://github.com/raspberrypi/documentation/blob/develop/documentation/asciidoc/computers/raspberry-pi/revision-codes.adoc#check-raspberry-pi-model-and-cpu-across-distributions
OUTPUT=$(cat /proc/device-tree/compatible | tr '\0,' '\t' | awk '{print $4}')
case "$OUTPUT" in
    "bcm2837")
        export VISERON_RASPBERRYPI3=true
        printf "true" > /var/run/environment/VISERON_RASPBERRYPI3
        log_info "Running on an RPi3"
        ;;

    "bcm2711")
        export VISERON_RASPBERRYPI4=true
        printf "true" > /var/run/environment/VISERON_RASPBERRYPI4
        log_info "Running on an RPi4"
        ;;

    *)
        log_info "Not running on any supported RPi"
esac
log_info "*********************** Done *****************************"
